import os, re, urllib.parse
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from .config import WorkspaceConfig
from .registry import Registry
from .security import redact

AI_OWNED_MARKER = '<!-- GENERATED BY DURABLE MEDIA PIPELINE (AI-OWNED) - DO NOT MANUALLY EDIT -->'
DEFAULT_DAILY_NOTES_DIR = 'data/obsidian/daily'

def escape_markdown(text: str) -> str:
    if not isinstance(text, str):
        text = str(text)
    # Escape markdown link brackets
    return text.replace('[', '\\[').replace(']', '\\]')

def escape_link_path(path_str: str) -> str:
    # URL quote path preserving slashes
    parts = path_str.replace('\\', '/').split('/')
    quoted_parts = [urllib.parse.quote(p) for p in parts]
    return '/'.join(quoted_parts)

def generate_manifest_link_block(manifest: dict[str, Any], rel_path: str | None = None) -> str:
    safe = redact(manifest)
    project = safe.get('project') or 'unnamed-project'
    task_id = safe.get('task_id') or 'unknown-task'
    agent = safe.get('agent') or 'unknown-agent'
    prompt_hash = safe.get('prompt_hash') or 'omitted'
    context_id = safe.get('context_id')

    lines = [
        f"#### Project Manifest: {escape_markdown(project)}",
        f"- **Task ID**: `{escape_markdown(task_id)}`",
        f"- **Agent**: `{escape_markdown(agent)}`",
        f"- **Prompt Hash**: `{escape_markdown(prompt_hash)}`",
    ]
    if context_id:
        lines.append(f"- **Context ID**: `{escape_markdown(context_id)}`")

    if rel_path:
        safe_rel = escape_link_path(rel_path)
        filename = escape_markdown(Path(rel_path).name)
        lines.append(f"- **Manifest File**: [{filename}]({safe_rel})")

    artifacts = safe.get('artifacts', [])
    if artifacts:
        lines.append("- **Artifacts**:")
        # Sort artifacts deterministically by path
        sorted_artifacts = sorted(artifacts, key=lambda a: a.get('artifact_path', a.get('path', '')))
        for a in sorted_artifacts:
            path = a.get('artifact_path', a.get('path', ''))
            aid = a.get('asset_id') or 'unregistered'
            sha = (a.get('sha256') or '')[:12]
            role = a.get('role') or 'master'
            kind = a.get('kind') or 'file'
            safe_p = escape_link_path(path)
            lines.append(f"  - `{escape_markdown(aid)}` ({escape_markdown(kind)}/{escape_markdown(role)}, sha256:{sha}) -> [{escape_markdown(path)}]({safe_p})")

    return '\n'.join(lines)

def generate_receipt_link_block(receipt: dict[str, Any]) -> str:
    safe = redact(receipt)
    rid = safe.get('receipt_id') or 'unknown-receipt'
    platform = safe.get('platform') or 'unknown-platform'
    account = safe.get('account') or 'default'
    url = safe.get('url') or ''
    ext_id = safe.get('external_id') or 'none'
    jid = safe.get('job_id') or 'unknown-job'
    idempotency_key = safe.get('idempotency_key') or ''
    verified_at = safe.get('verified_at') or safe.get('created_at') or ''

    lines = [
        f"#### Publish Receipt: `{escape_markdown(rid)}`",
        f"- **Platform**: `{escape_markdown(platform)}`",
        f"- **Account/Destination**: `{escape_markdown(account)}`",
        f"- **External ID**: `{escape_markdown(ext_id)}`",
        f"- **Status**: `verified`",
    ]
    if url:
        safe_url = escape_link_path(url)
        lines.append(f"- **Post URL**: [{escape_markdown(url)}]({safe_url})")
    lines.append(f"- **Job ID**: `{escape_markdown(jid)}`")
    if idempotency_key:
        lines.append(f"- **Idempotency Key**: `{escape_markdown(idempotency_key)}`")
    if verified_at:
        lines.append(f"- **Verified At**: `{escape_markdown(verified_at)}`")

    return '\n'.join(lines)

def generate_daily_note_content(date_str: str, manifests: list[tuple[dict, str]], receipts: list[dict]) -> str:
    lines = [
        AI_OWNED_MARKER,
        "",
        f"## Durable Media Daily Summary — {escape_markdown(date_str)}",
        "",
        f"*Generated on {datetime.now(timezone.utc).isoformat()}*",
        "",
        "### Project Manifests",
    ]
    if manifests:
        for m_data, rel_p in sorted(manifests, key=lambda m: (m[0].get('project') or '', m[0].get('task_id') or '')):
            lines.append("")
            lines.append(generate_manifest_link_block(m_data, rel_p))
    else:
        lines.append("")
        lines.append("*No project manifests recorded for this date.*")

    lines.append("")
    lines.append("### Published Receipts")
    if receipts:
        for rec in sorted(receipts, key=lambda r: (r.get('platform') or '', r.get('receipt_id') or '')):
            lines.append("")
            lines.append(generate_receipt_link_block(rec))
    else:
        lines.append("")
        lines.append("*No publish receipts recorded for this date.*")

    lines.append("")
    return '\n'.join(lines)

def write_daily_note(
    cfg: WorkspaceConfig,
    registry: Registry,
    date_str: str | None = None,
    vault_dir: Path | str | None = None,
) -> Path:
    if not date_str:
        date_str = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    if vault_dir:
        out_dir = Path(vault_dir).resolve()
        out_dir.mkdir(parents=True, exist_ok=True)
    else:
        out_dir = cfg.root / DEFAULT_DAILY_NOTES_DIR
        out_dir.mkdir(parents=True, exist_ok=True)

    out_file = out_dir / f'{date_str}.md'

    # Safety check: Never mutate or overwrite human-authored notes
    if out_file.exists():
        first_chunk = out_file.read_text(encoding='utf-8', errors='ignore')[:256]
        if AI_OWNED_MARKER not in first_chunk:
            raise PermissionError(
                f'Target file {out_file} exists and lacks AI-owned header. '
                'Refusing to overwrite human-authored note.'
            )

    # Collect receipts for date
    receipt_rows = registry.conn.execute(
        "SELECT * FROM receipts WHERE created_at LIKE ? OR verified_at LIKE ? ORDER BY receipt_id",
        (f'{date_str}%', f'{date_str}%')
    ).fetchall()
    receipts = [dict(r) for r in receipt_rows]

    # Collect manifests from cfg.root / manifests
    manifest_tuples = []
    manifest_dir = cfg.root / 'manifests'
    if manifest_dir.is_dir():
        import json
        for mf in sorted(manifest_dir.glob('*.json')):
            try:
                m_data = json.loads(mf.read_text(encoding='utf-8'))
                rel = str(mf.relative_to(cfg.root))
                # If manifest has created_at matching date, or if file modified date matches
                m_date = (m_data.get('created_at') or '')[:10]
                if not m_date:
                    m_date = datetime.fromtimestamp(mf.stat().st_mtime, tz=timezone.utc).strftime('%Y-%m-%d')
                if m_date == date_str:
                    manifest_tuples.append((m_data, rel))
            except Exception:
                continue

    content = generate_daily_note_content(date_str, manifest_tuples, receipts)
    out_file.write_text(content, encoding='utf-8')
    return out_file
