from typing import Protocol
class Publisher(Protocol):
 def validate_target(self,target): ...
 def create_upload(self,job): ...
 def upload(self,remote,file_path): ...
 def wait_until_ready(self,remote): ...
 def publish(self,remote,job): ...
 def verify(self,result): ...
 def rollback_or_cleanup(self,remote): ...
